Repository im-na0/wiki, pull requests merged in 2023-09, with the labels that each got.

#10 Feat: 헤더 푸터 수정
  public/fe3-wiki-logo.png
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/styles/Footer.css
  src/styles/Header.css
Labels: enhancement

#11 Feature: 로그인, 회원가입 페이지 마크업
  package-lock.json
  package.json
  src/components/SignUp/Navigation.tsx
  src/components/SignUp/Pagination.tsx
  src/components/SignUp/Register/EndRegister.tsx
  src/components/SignUp/Register/StartRegister.tsx
  src/components/SignUp/Register/UserRegister.tsx
  src/components/SignUp/SignUpEmail.tsx
  src/components/SignUp/Title.tsx
  src/components/signin/SignInEmail.tsx
  src/components/signin/SignInGoogle.tsx
  src/libs/firebase.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/router/Router.tsx
Labels: enhancement

#12 Feat: Timer 페이지 마크업
  src/components/Timer/TimerApp.tsx
  src/pages/Timer.tsx
Labels: enhancement

#21 Refactor: Wiki 페이지 Nav 폴더 토글 및 렌더링 이슈 해결
  src/components/Wiki/Nav.tsx
Labels: refactor

#22 Feat: 직원 리스트 페이지 모달 마크업
  src/components/Employee/AddMemberForm.tsx
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/CardAddMember.tsx
  src/components/Employee/MemberControlMenu.tsx
  src/components/Employee/MemberExportBtn.tsx
  src/components/Employee/MemberFilter.tsx
  src/components/Employee/MemberHeading.tsx
  src/components/Employee/MemberSearch.tsx
  src/components/Employee/MemberTable.tsx
  src/components/Signin/SignInEmail.tsx
  src/components/Signin/SignInGoogle.tsx
  src/components/Timer/TimerApp.tsx
  src/components/common/CustomForm/CustomUpload.tsx
  src/components/common/CustomForm/index.tsx
  src/constant/member.tsx
  src/layouts/Header.tsx
  src/pages/Employee.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: enhancement

#29 Refactor: 직원 상세정보 페이지 상태관리 이슈 해결
  src/components/Employee/AddMemberForm.tsx
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberForm.tsx
  src/components/Employee/MemberProfile.tsx
  src/pages/EmployeeDetail.tsx
Labels: refactor

#34 Feat: 프로젝트 페이지 firebase 데이터 연동
  src/components/project/ProjectAssignee.tsx
  src/components/project/ProjectDate.tsx
  src/components/project/ProjectDetailInfo.tsx
  src/components/project/ProjectDragDrop.tsx
  src/components/project/ProjectDraggable.tsx
  src/components/project/ProjectDroppable.tsx
  src/components/project/ProjectListItem.tsx
  src/components/project/ProjectListSider.tsx
  src/components/project/ProjectMdEditor.tsx
  src/components/project/ProjectMdViewer.tsx
  src/components/project/ProjectNewForm.tsx
  src/components/project/ProjectSider.tsx
  src/components/project/ProjectTeams.tsx
  src/hooks/project/fileUploadValidation.ts
  src/hooks/project/updateOrder.ts
  src/hooks/project/useMutationDelProject.tsx
  src/hooks/project/useMutationNewProject.tsx
  src/hooks/project/useQueryProject.tsx
  src/hooks/project/useQueryProjectAllList.tsx
  src/index.tsx
  src/libs/firebase.ts
  src/libs/firestore.ts
  src/pages/ProjectDetail.tsx
  src/pages/ProjectEdit.tsx
  src/pages/ProjectList.tsx
  src/router/Router.tsx
  src/store/project.ts
  src/styles/Header.css
  src/styles/Project.css
Labels: enhancement

#35 Feat: 직원 리스트 페이지 Firebase 연동
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/MemberControlMenu.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberExportBtn.tsx
  src/components/Employee/MemberForm.tsx
  src/components/Employee/MemberHeading.tsx
  src/components/Employee/MemberList.tsx
  src/components/Employee/MemberProfile.tsx
  src/components/Employee/MemberTable.tsx
  src/components/common/CustomForm/CustomUpload.tsx
  src/components/common/CustomForm/index.tsx
  src/components/common/CustomTable/index.tsx
  src/constant/member.tsx
  src/data/formSource.ts
  src/data/tableColumns.tsx
  src/hook/Employee/useDeleteData.ts
  src/hook/Employee/useFetchData.ts
  src/libs/firebase.ts
  src/pages/Employee.tsx
  src/store/member.tsx
  src/type/form.ts
Labels: enhancement, refactor

#40 Fix: firebase.ts 수정
  src/libs/firebase.ts
Labels: bug

#41 Feat: 멤버 리스트 페이지 검색/필터링 기능 구현
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberFilter.tsx
  src/components/Employee/MemberList.tsx
  src/components/Employee/MemberSearch.tsx
  src/components/Employee/MemberTable.tsx
  src/data/actionColumn.tsx
  src/data/tableColumns.tsx
  src/hooks/Employee/useDeleteData.ts
  src/hooks/Employee/useFetchData.ts
Labels: enhancement

#43 Feat: 메인 페이지 마크업
  package-lock.json
  package.json
  src/components/Main/MainProjectWidget.tsx
  src/components/Main/MainSwiper.tsx
  src/components/Main/MainTeam.tsx
  src/components/Main/MainWidget.tsx
  src/components/Main/MainWikiWidget.tsx
  src/components/project/ProjectDragDrop.tsx
  src/constant/main.tsx
  src/hooks/main/useQueryWidget.tsx
  src/index.tsx
  src/libs/firestore.ts
  src/pages/Main.tsx
  src/styles/Main.css
Labels: enhancement

#47 Feat: Timer DB 연동 및 추가기능 구현
  src/components/Timer/TimerApp.tsx
  src/components/WorkTime/WorkCalendar.tsx
  src/components/WorkTime/WorkTimeList.tsx
  src/layouts/Header.tsx
  src/pages/Timer.tsx
  src/router/Router.tsx
Labels: Feat

#48 Feat: 직원 상세정보 페이지 Firebase 연동
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberList.tsx
  src/components/Employee/MemberProfile.tsx
  src/components/Employee/MemberSearch.tsx
  src/components/Employee/MemberTable.tsx
  src/components/common/CustomTable/index.tsx
  src/data/tableColumns.tsx
  src/hooks/Employee/useFetchData.ts
  src/hooks/Employee/useMemberMutaion.ts
  src/pages/EmployeeDetail.tsx
  src/router/Router.tsx
Labels: Feat

#51 Refactor: 리팩토링 및 스토리지 이미지 분리
  src/assets/wiki.svg
  src/components/Wiki/WikiDefaultPage.tsx
  src/components/Wiki/WikiEditor.tsx
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiPage.tsx
  src/components/Wiki/WikiSelect.tsx
  src/components/Wiki/WikiSubPage.tsx
  src/components/Wiki/WikiViewer.tsx
  src/hooks/Wiki/api.ts
  src/pages/Wiki.tsx
Labels: refactor

#54 Feat: Project 팀, 멤버 부분 추가 작업
  public/wiki.svg
  src/components/project/ProjectDetailDefault.tsx
  src/components/project/ProjectNewForm.tsx
  src/hooks/project/useQueryProjectEdit.tsx
  src/libs/firestore.ts
  src/pages/ProjectEdit.tsx
  src/pages/ProjectList.tsx
  src/pages/ProjectNew.tsx
Labels: Feat

#55 Feat: Wiki 기타 기능 추가
  src/components/Wiki/WikiDefaultPage.tsx
  src/components/Wiki/WikiEditor.tsx
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiSelect.tsx
  src/components/Wiki/WikiSubPage.tsx
  src/components/Wiki/WikiViewer.tsx
  src/hooks/Wiki/api.ts
  src/store/wiki.ts
Labels: Feat, refactor

#59 Refactor : 회원 가입 User DB 구조 변경
  src/components/SignUp/Register/EndRegister.tsx
  src/components/SignUp/Register/StartRegister.tsx
  src/components/SignUp/Register/UserRegister.tsx
  src/store/signup.ts
Labels: refactor

#61 Feat: 캘린더 기능 추가 및 일부 오류 수정
  src/components/Timer/TimerApp.tsx
  src/components/WorkTime/WorkCalendar.tsx
  src/components/WorkTime/WorkTimeList.tsx
  src/hooks/Timer/useQueryWorkTime.tsx
  src/libs/firestore.ts
  src/styles/WorkTime.css
Labels: Feat

#62 Feat : 정보 수정 시 기존 정보 삭제
  src/components/SignUp/Register/UserRegister.tsx
Labels: Feat

#73 Feat: 프로젝트 페이지 필터링 추가
  src/components/project/ProjectDetailInfo.tsx
  src/components/project/ProjectListItem.tsx
  src/components/project/ProjectListSider.tsx
  src/components/project/ProjectNewFormSkeleton.tsx
  src/components/project/ProjectSider.tsx
  src/hooks/project/useMutationDelProject.tsx
  src/hooks/project/useMutationNewProject.tsx
  src/hooks/project/useQueryParam.ts
  src/hooks/project/useQueryProject.tsx
  src/hooks/project/useQueryProjectAllList.tsx
  src/hooks/project/useQueryProjectEdit.tsx
  src/libs/firestore.ts
  src/pages/ProjectDetail.tsx
  src/pages/ProjectEdit.tsx
  src/store/project.ts
  src/styles/Project.css
Labels: Feat

#74 Feat: 출퇴근 페이지 로딩 애니메이션 구현 및 오류 수정
  src/components/Timer/TimerApp.tsx
  src/components/WorkTime/WorkCalendar.tsx
  src/components/WorkTime/WorkTimeList.tsx
  src/layouts/Header.tsx
  src/styles/WorkTime.css
Labels: Feat

#75 Fix: 회원가입/로그인 문제 해결
  package-lock.json
  package.json
  src/App.tsx
  src/components/SignUp/Register/EndRegister.tsx
  src/components/SignUp/Register/StartRegister.tsx
  src/components/SignUp/Register/UserRegister.tsx
  src/components/SignUp/SignUpEmail.tsx
  src/components/Signin/AuthStateChanged.tsx
  src/components/Signin/SignInEmail.tsx
  src/components/Signin/SignInGoogle.tsx
  src/hooks/SignIn/Navigation.tsx
  src/hooks/SignIn/useModal.ts
  src/layouts/Header.tsx
  src/libs/firebase.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/router/Router.tsx
  src/store/sign.ts
  src/store/signin.ts
  src/styles/Header.css
Labels: bug

#79 Feat: Wiki 페이지 팀 파일 유저 정보 렌더링 및 기타 기능 추가
  src/components/Main/MainWidget.tsx
  src/components/Main/MainWikiWidget.tsx
  src/components/Wiki/WikiDefaultPage.tsx
  src/components/Wiki/WikiEditor.tsx
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiSelect.tsx
  src/components/Wiki/WikiSubPage.tsx
  src/components/Wiki/WikiTeamNav.tsx
  src/components/Wiki/WikiViewer.tsx
  src/hooks/Wiki/api.ts
  src/store/wiki.ts
Labels: Feat, refactor

#76 Feat: 팀 상세정보 페이지 업로드 로딩 기능
  src/components/Employee/EditMemberSelect.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/TeamDetailInfo.tsx
  src/styles/Employee.css
Labels: Feat

#82 Feat: 로그인 유저정보 연동
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiSubPage.tsx
  src/components/Wiki/WikiTeamNav.tsx
  src/components/Wiki/WikiViewer.tsx
  src/hooks/Wiki/api.ts
  src/store/wiki.ts
Labels: Feat

#83 Feat: 프로젝트 페이지 본인 소속 팀만 불러오는 기능
  src/components/project/ProjectDragDrop.tsx
  src/components/project/ProjectListSider.tsx
  src/components/project/ProjectSider.tsx
  src/hooks/main/useQueryWidget.ts
  src/hooks/project/useMutationDelProject.ts
  src/hooks/project/useMutationNewProject.ts
  src/hooks/project/useQueryProject.ts
  src/hooks/project/useQueryProjectAllList.ts
  src/hooks/project/useQueryProjectEdit.ts
  src/hooks/project/useQueryProjectTeam.ts
  src/pages/Project.tsx
Labels: Feat

#85 Feat : 내 정보 수정 시 유저 정보 보이게 하기
  src/components/SignUp/Register/UserRegister.tsx
  src/styles/Header.css
Labels: Feat

#90 Style: 회원가입 / 로그인 화면 디자인 수정
  public/secure_login.svg
  public/team_up.svg
  src/App.tsx
  src/components/SignUp/Register/UserRegister.tsx
  src/components/SignUp/Title.tsx
  src/components/Signin/SignInGoogle.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
Labels: style

#92 Fix: 스타일드 컴포넌트 props 에러 해결
  src/components/Main/MainWikiWidget.tsx
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiSelect.tsx
  src/components/Wiki/WikiTeamNav.tsx
  src/components/Wiki/WikiViewer.tsx
Labels: bug

#94 Style: 프로젝트 목록이 많으면 스크롤바 생기게 변경
  src/hooks/project/useMutationNewProject.ts
  src/pages/ProjectDetail.tsx
  src/styles/Project.css
Labels: style

#97 Style: 위키페이지 반응형 스타일링
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiTeamNav.tsx
  src/components/Wiki/WikiViewer.tsx
  src/pages/Wiki.tsx
Labels: style

#99 Refactor: 프로젝트 페이지 리팩토링
  src/components/Main/MainSwiper.tsx
  src/components/Main/MainTeam.tsx
  src/components/Main/MainWidget.tsx
  src/components/Main/MainWikiWidget.tsx
  src/components/project/ProjectAssignee.tsx
  src/components/project/ProjectDate.tsx
  src/components/project/ProjectDetailDefault.tsx
  src/components/project/ProjectDragDrop.tsx
  src/components/project/ProjectDraggable.tsx
  src/components/project/ProjectDroppable.tsx
  src/components/project/ProjectListItem.tsx
  src/components/project/ProjectListSider.tsx
  src/components/project/ProjectSider.tsx
  src/components/project/ProjectTeams.tsx
  src/hooks/project/useQueryProjectAllList.ts
  src/hooks/project/useQueryProjectList.ts
  src/pages/Project.tsx
  src/pages/ProjectList.tsx
  src/router/Router.tsx
Labels: refactor

#103 Feat: 멤버 삭제 시 팀 콜렉션 userId 삭제
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberList.tsx
  src/components/Employee/MemberSelectTeam.tsx
  src/components/Employee/MemberTable.tsx
  src/components/Employee/Team/AddTeamModal.tsx
  src/components/Employee/Team/TeamCard.tsx
  src/components/Employee/Team/TeamTable.tsx
  src/components/common/CustomForm/index.tsx
  src/constant/member.tsx
  src/data/tableColumns.tsx
  src/data/teamTableColumns.tsx
  src/hooks/Employee/useDeleteData.ts
  src/hooks/Employee/useMemberMutaion.ts
  src/hooks/Employee/useUpdateTeamForMember.ts
  src/type/form.ts
Labels: bug, Feat

#104 Feat: 위키 하위 파일들 접기 기능 추가
  src/components/Wiki/WikiDefaultPage.tsx
  src/components/Wiki/WikiEditor.tsx
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiSelect.tsx
  src/components/Wiki/WikiTeamNav.tsx
  src/components/Wiki/WikiViewer.tsx
Labels: Feat

#105 Feat: 캘린더 실시간 업데이트 기능 및 타이머 로직 추가
  src/components/Timer/TimerApp.tsx
  src/components/WorkTime/WorkCalendar.tsx
  src/hooks/Timer/useQueryWorkTime.tsx
  src/hooks/WorkTime/useQueryLeave.tsx
  src/libs/firestore.ts
Labels: Feat

#107 Fix : 빈 파일 생성 버그 수정
  src/components/Wiki/WikiNav.tsx
  src/components/Wiki/WikiSelect.tsx
  src/components/Wiki/WikiTeamNav.tsx
Labels: bug

#113 Docs: readme.md 작성을 위한 틀 제작
  README.md
  public/profiles/김미정.jpg
  public/profiles/김성겸.jpg
  public/profiles/노욱진.jpg
  public/profiles/박나영.jpg
  public/profiles/진종수.jpg
Labels: Docs

#111 Style: 팀 페이지 UI 작업 및 권한설정
  .firebaserc
  package-lock.json
  package.json
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberForm.tsx
  src/components/Employee/MemberList.tsx
  src/components/Employee/MemberProfile.tsx
  src/components/Employee/MemberSelectTeam.tsx
  src/components/Employee/MemberSider.tsx
  src/components/Employee/MemberTable.tsx
  src/components/Employee/Team/TeamCard.tsx
  src/components/Employee/Team/TeamDetailInfo.tsx
  src/components/Employee/Team/TeamList.tsx
  src/data/formSource.ts
  src/data/tableColumns.tsx
  src/hooks/Employee/useMemberMutaion.ts
  src/hooks/Employee/useUpdateTeamForMember.ts
  src/hooks/Employee/useUserAccess.ts
  src/store/member.tsx
  src/styles/Employee.css
  src/utils/formatDate.ts
Labels: Feat, style

#118 Style: 메인 슬라이더 이미지 및 내용 변경
  public/slide-bg01.jpg
  public/slide-bg02.jpg
  public/slide-bg03.jpg
  src/components/Main/MainSwiper.tsx
  src/components/Main/MainTeam.tsx
  src/components/Timer/TimerApp.tsx
  src/constant/main.tsx
Labels: style

#114 Style : 로그인/회원가입 페이지 수정 및 access 필드 생성
  public/index.html
  src/components/SignUp/Title.tsx
  src/components/Signin/SignInEmail.tsx
  src/components/Signin/SignInGoogle.tsx
  src/hooks/SignIn/useSign.ts
  src/hooks/SignIn/userRegister.ts
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  src/store/sign.ts
Labels: style

#124 Refactor: 타이머, 출퇴근 기록 페이지 리팩토링
  src/components/Timer/TimerApp.tsx
  src/components/WorkTime/WorkCalendar.tsx
  src/hooks/WorkTime/useQueryLeave.tsx
  src/libs/firestore.ts
Labels: refactor

#125 Docs: 프로젝트 페이지 readme.md 설명 추가
  README.md
  public/images/project-detail.png
  public/images/project-kanban.gif
  public/images/project-sorting.gif
  public/images/user-flow.png
Labels: Docs

#130 Docs: 타이머, 출퇴근 기록 페이지 Readme.md 추가
  README.md
  public/images/timer-btnonoff.mov
  public/images/timer-default.png
  public/images/worktime-default.png
  public/images/worktime-listcalendar.mov
  public/images/worktime-teamlist.mov
Labels: Docs

#131 Refactor: 직원/팀 페이지 코드 리팩토링
  src/components/Employee/AddMemberModal.tsx
  src/components/Employee/MemberDetailInfo.tsx
  src/components/Employee/MemberList.tsx
  src/components/Employee/MemberTable.tsx
  src/components/Employee/Team/AddMemberSelect.tsx
  src/components/Employee/Team/AddTeamModal.tsx
  src/components/Employee/Team/EditMemberSelect.tsx
  src/components/Employee/Team/TeamCard.tsx
  src/components/Employee/Team/TeamDetailInfo.tsx
  src/components/Employee/Team/TeamForm.tsx
  src/components/Employee/Team/TeamLeaderSelect.tsx
  src/components/Employee/Team/TeamList.tsx
  src/components/Employee/Team/TeamMemberSelect.tsx
  src/constant/member.tsx
  src/data/tableColumns.tsx
  src/hooks/Employee/useFetchData.ts
  src/hooks/Employee/useMemberMutaion.ts
  src/hooks/Employee/useUpdateTeamForMember.ts
  src/hooks/Employee/useUserAccess.ts
  src/styles/Employee.css
  src/utils/formatDepartment.ts
Labels: refactor

#129 Refactor : ReadMe 및 시작페이지 수정
  README.md
  src/components/SignUp/Register/StartRegister.tsx
Labels: refactor

#133 Docs: 타이머 및 출퇴근 기록 페이지 readme.md 일부 수정
  README.md
  public/images/timer-btnonoff.gif
  public/images/timer-btnonoff.mov
  public/images/worktime-listcalendar.gif
  public/images/worktime-listcalendar.mov
  public/images/worktime-teamlist.gif
  public/images/worktime-teamlist.mov
Labels: Docs

#134 Docs: 직원 정보 페이지 readme.md 작성
  README.md
  public/images/employee-list.png
  public/images/employee-table.gif
  public/images/employee-team.gif
  public/images/team-list.png
Labels: Docs

#137 Docs: 타이머, 출퇴근 기록 페이지 readme.md 수정
  public/images/timer-btnonoff.gif
  public/images/worktime-listcalendar.gif
  public/images/worktime-teamlist.gif
Labels: Docs

#126 Docs: 위키 페이지 리드미 설명 추가
  README.md
  public/images/wiki-IntroImage.png
  public/images/wiki-IntroImage2.png
  public/images/wiki-image.png
  public/profiles/노욱진.jpg
  src/constant/main.tsx
Labels: Docs

#138 Docs: 메인 페이지 스샷 추가 + 미정님 요청사항 수정
  README.md
  public/images/project-main-page.png
Labels: Docs
